; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

<<<<<<< HEAD
<<<<<<< HEAD
; [env:hornbill32minima]
; platform = espressif32
; board = hornbill32minima
; framework = arduino

[env:esp32-c3-devkitm-1]
=======
[env:esp32-c3]
>>>>>>> c7217bb77c9a6fc445300e92fc5fcb44f41263cc
=======
[env:esp32-c3]
>>>>>>> ea0e02733f0fd5abee21d5058c2a828e14036903
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
<<<<<<< HEAD
<<<<<<< HEAD
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
; monitor_port = /dev/ttyACM1
=======
upload_speed = 115200
>>>>>>> c7217bb77c9a6fc445300e92fc5fcb44f41263cc
=======
upload_speed = 115200
>>>>>>> ea0e02733f0fd5abee21d5058c2a828e14036903
