import {
    HorizontalBox,
    Palette,
    VerticalBox,
    Switch,
    Button,
} from "std-widgets.slint";
import { Theme } from "theme.slint";
import { ColorBar } from "colour_bar.slint";
import { IconDisplay, IconSet } from "lucida.slint";

export component DataDump inherits HorizontalBox {

    in property <bool> enable_control;
    in property <bool> wifi_connected;
    in property <bool> wifi_dumping;

    in property <string> downloaded_bytes;
    in property <string> remote_only_bytes;

    callback data_transfer_all();
    callback data_transfer_cancel();

    out property <int> download_bar_width: download-bar.width / 1phx;
    in property <image> download_bar_image;

    private property <int> reclick_dump_secs: 0;
    reclick-dump-timer := Timer {
        interval: 1s;
        running: true;

        triggered => {
            reclick_dump_secs += 1;
        }
    }

    Rectangle {
        background: enable_control ? Palette.background : Palette.alternate-background;
        width: 100%;
        border-radius: 4pt;
        border-color: Palette.border;
        border-width: 1px;

        VerticalBox {
            alignment: start;
            spacing: 0pt;

            HorizontalBox {
                spacing: 4pt;

                VerticalLayout {
                    alignment: center;
                    IconDisplay {

                        icon: IconSet.Download;
                        stroke: Palette.foreground;
                        stroke-width: 2;
                        size: 25pt;
                    }
                }

                Text {
                    text: "Data Download";
                    font-weight: Theme.bold-font-weight;
                    font-size: Theme.large-font-size;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }

                Rectangle {
                    horizontal-stretch: 1.0;
                }
            }

            HorizontalBox {

                Button {
                    primary: true;
                    text: wifi_dumping ? "Cancel" : "Start";
                    enabled: enable_control && reclick_dump_secs >= 2;
                    width: Theme.first-col;

                    clicked => {
                        if (wifi_dumping) {
                            data_transfer_cancel()
                        } else {
                            data_transfer_all()
                        }

                        reclick-dump-timer.restart();
                        reclick_dump_secs = 0;
                    }
                }

                VerticalLayout {

                    Text {
                        text: "Sync missing data";
                        font-weight: Theme.bold-font-weight;
                        vertical-alignment: center;
                    }

                    Text {
                        text: "Begin copying missing data from the module to this PC.";
                        vertical-alignment: center;
                    }
                }

                Rectangle {
                    horizontal-stretch: 1.0;
                }

                // HorizontalLayout {
                //     alignment: start;
                //     width: 120pt;
                //     spacing: 5pt;

                //     IconDisplay {
                //         icon: wifi_connected ? IconSet.Route : IconSet.RouteOff;
                //         stroke: wifi_connected ? Theme.ok-green : Theme.warn-orange;
                //         stroke-width: 1.5;
                //         size: 25pt;
                //     }

                //     Text {
                //         text: wifi_connected ? "Connected" : "Disconnected";
                //         vertical-alignment: center;
                //     }
                // }

                HorizontalLayout {
                    alignment: start;
                    width: 120pt;
                    spacing: 5pt;

                    VerticalLayout {
                        alignment: center;
                        IconDisplay {
                            icon: IconSet.Download;
                            stroke: wifi_dumping ? Theme.ok-green : Theme.warn-orange;
                            stroke-width: 1.5;
                            size: 25pt;
                        }
                    }

                    Text {
                        text: wifi_dumping ? "Transferring" : "Standby";
                        vertical-alignment: center;
                    }
                }
            }

            VerticalBox {

                HorizontalLayout {

                    Text {
                        text: "Downloaded Data";
                        font-weight: Theme.bold-font-weight;
                        vertical-alignment: center;
                    }

                    Rectangle {
                        horizontal-stretch: 5.0;
                    }

                    HorizontalLayout {
                        alignment: start;
                        spacing: 4pt;

                        Rectangle {
                            background: Theme.ok-green;
                            border-radius: 3pt;
                            width: 1.5rem;
                        }

                        Text {
                            text: "Downloaded";
                            vertical-alignment: center;
                        }
                    }

                    HorizontalLayout {
                        alignment: start;
                        spacing: 4pt;

                        Rectangle {
                            background: Theme.err-red;
                            border-radius: 3pt;
                            width: 1.5rem;
                        }

                        Text {
                            text: "Remote-only";
                            vertical-alignment: center;
                        }
                    }

                    HorizontalLayout {
                        alignment: start;
                        spacing: 4pt;

                        Rectangle {
                            background: Theme.empty-grey;
                            border-radius: 3pt;
                            width: 1.5rem;
                        }

                        Text {
                            text: "Empty";
                            vertical-alignment: center;
                        }
                    }
                }

                download-bar := ColorBar {
                    segment-image: download_bar_image;
                }
            }
        }
    }
}
