import { HorizontalBox, Palette, } from "std-widgets.slint";


component Circle inherits VerticalLayout {
    in property <length> radius;
    in property <color> fill;

    vertical-stretch: 0;
    alignment: center;
    HorizontalLayout {
        alignment: center;
        horizontal-stretch: 0;
        Rectangle {
            width: root.radius * 2;
            height: root.radius * 2;
            border-radius: root.radius;
            background: root.fill;
        }
    }
}


export component StatusBar inherits Rectangle {
    in property <string> subject: "Subject";
    in property <bool> attached: false;
    in property <bool> connected: false;
    in property <string> instruction: "";

    horizontal-stretch: 1;
    height: 40px;

    background: Palette.alternate-background;
    
    HorizontalLayout {
        padding: 8px;
        spacing: 8px;

        Text {
            horizontal-stretch: 0;

            text: root.subject;
            font-weight: 700;
            font-size: 15px;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        Rectangle {
            horizontal-stretch: 1;
        }

        if (!root.connected) : Text {
            text: root.instruction;
            font-size: 15px;
            font-italic: true;
            font-weight: 300;

            color: orange;

            vertical-alignment: center;
            horizontal-alignment: center;
        }

        Rectangle {
            horizontal-stretch: 1;
        }

        Text {
            horizontal-stretch: 0;

            text: "Attached";
            font-size: 15px;
            vertical-alignment: center;
        }

        Circle { radius: 6px; fill: attached ? green : red; }

        Rectangle { width: 3px; }

        Text {
            horizontal-stretch: 0;

            text: "Connected";
            font-size: 15px;
            vertical-alignment: center;
        }

        Circle { radius: 6px; fill: connected ? green : red; }
    }
}
