import {
    HorizontalBox,
    Palette,
} from "std-widgets.slint";

import { Theme } from "theme.slint";


component Circle inherits VerticalLayout {
    in property <color> fill;

    private property <length> radius: 0.7rem;

    vertical-stretch: 0;
    alignment: center;
    HorizontalLayout {
        alignment: center;
        horizontal-stretch: 0;
        Rectangle {
            width: root.radius * 2;
            height: root.radius * 2;
            border-radius: root.radius;
            background: root.fill;
        }
    }
}


export component StatusBar inherits Rectangle {
    in property <string> subject: "Subject";
    in property <bool> attached: false;
    in property <bool> connected: false;
    in property <string> instruction: "";

    horizontal-stretch: 1;
    height: 40pt;

    background: Palette.alternate-background;

    HorizontalLayout {
        padding: 8pt;
        spacing: 8pt;

        Text {
            horizontal-stretch: 0;

            text: root.subject;
            font-weight: Theme.bold-font-weight;
            font-size: 1.2rem;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        Rectangle {
            horizontal-stretch: 1;
        }

        if (!root.connected): Text {
            text: root.instruction;
            font-size: 1.2rem;
            font-italic: true;
            font-weight: Theme.default-font-weight;

            color: orange;

            vertical-alignment: center;
            horizontal-alignment: center;
        }

        Rectangle {
            horizontal-stretch: 1;
        }

        Text {
            horizontal-stretch: 0;

            text: "Attached";
            font-size: 1.2rem;
            vertical-alignment: center;
        }

        Circle {
            fill: attached ? green : red;
        }

        Rectangle {
            width: 3px;
        }

        Text {
            horizontal-stretch: 0;

            text: "Connected";
            font-size: 1.2rem;
            vertical-alignment: center;
        }

        Circle {
            fill: connected ? green : red;
        }
    }
}
