
export global Theme {
    out property <length> default-font-size: 13pt;
    out property <int> default-font-weight: 500;
    out property <string> default-font-family: "Roboto";

    out property <int> bold-font-weight: 900;

    out property <color> empty-grey: #AAAAAA;
    out property <color> ok-green: #27ae60;
    out property <color> err-red: #ED0112;
    out property <color> warn-orange: #e67e22;
    out property <color> active-blue: #1155EE;
}
